### ISSUE TITLE
Plaintext credentials

### ISSUE THREAD

**Issue by hbrylkowski** [InvidHead/Keras_FB#1]
Currently we need to put our facebook username and password, it would be much better if there would be a possibility to provide API key and secret instead - API keys can have limited scope of permissions, and It is easy to block them if they're compromised.

**Comment by kotobukki** [comment]
**Great idea!** We will make an update in a few days.
If you would like, you are also welcomed to contribute!

**Comment by kotobukki** [comment]
Update: It's impossible to implement such method with current library(FBChat), as a result we decide to move to the original API provided by FB.
The update will be made in a few days.
